### ISSUE TITLE
Improve const-correctness

### ISSUE THREAD

**Issue by elfring** [Matthias-Wandel/imgcomp#1]
I suggest to add the key word “const” to the type specifiers for parameters like the following.
- Directory (function “[GetSortedDir](https://github.com/Matthias-Wandel/imgcomp/blob/9044f133c7f4baeaafb49773875b9ff4edb35afb/src/util.c#L152)”)
- FileName (function “[LoadJPEG](https://github.com/Matthias-Wandel/imgcomp/blob/9044f133c7f4baeaafb49773875b9ff4edb35afb/src/jpeg2mem.c#L42)”)

Would you like to apply the advices from [an article](https://en.wikipedia.org/wiki/Const_%28computer_programming%29#Consequences "Description for const-correctness") to more places in your source files?

**Comment by Matthias-Wandel** [comment]
Send me a pull request if you want this changed.

**Comment by Matthias-Wandel** [comment]
I don't know how to use github very well.  I don't know why I referred to this with an unrelated commit.  At any rate, this is just a pedantic change, so if you want it, send me a pull request, otherwise not worth addressing.

**Comment by fairclothjm** [comment]
@Matthias-Wandel the unrelated commit referenced this issue because @mcbeardface's pull request had two commits that he himself made. One of these commits referenced his fork's own first pull request with the `#1`. When _you_ merged his pull request, Github saw that `#1` from one of his commits and then referenced #1 in your repo. Which happens to be this issue.

That github feature can be nice but it doesn't always make sense.

Hope that helps and doesn't just make it more confusing! :)
