### ISSUE TITLE
Not compatible OOB with newer Pis that are shipped with libcamera instead of raspisitll

### ISSUE THREAD

**Issue by ahartschen** [Matthias-Wandel/imgcomp#38]
I've been tinkering with the code a little to get this to run on a Pi running the latest version of Raspberry Pi OS with a Pi Camera Module v3 and haven't had any luck.  From what I understand `libcamera-still` should mostly be a drop in replacement for `raspistill`. I tried updating the `acquire_cmd` in the conf file and then replaced various references to `raspistill` in src/start_raspistill.c and I was still seeing some errors on startup.

**Comment by Matthias-Wandel** [comment]
What errors are you seeing?

**Comment by ahartschen** [comment]
Here's what I see on startup. I haven't dug into this too much, but `-w` is a valid option for `libcamera-still`. I'm not too experienced with C, so maybe it's something to do with the command being a few characters longer?

```
Imgcomp version 0.97 (Mar 2021) by Matthias Wandel

Configuration parameters:
    'aquire_cmd' = 'libcamera-still -q 10 -ex antishake -n -th none -p 1000,0,600,450 -w 1600 -h 1200 -o /ramdisk/out%05d.jpg -t 0 -tl 1000'
    'followdir' = '/ramdisk'
    'spurious' = '1'
    'brmonitor' = '0'
    'savedir' = 'images'
    'savenames' = '%y%m%d/%H/%m%d-%H%M%S'
    'timelapse' = '1800'
    'sensitivity' = '300'
    'logtofile' = '/ramdisk/log.txt'
    'movelognames' = 'images/%y%m%d/%H/Log.html'
    Source directory = /ramdisk, follow=1
    Save to dir images
    Timelapse interval 1800 seconds
libcamera-still: no process found
Closing Libcamera application(frames displayed 0, dropped 0)
Camera stopped!
Tearing down requests, buffers and configuration
Camera closed
ERROR: *** unrecognised option '-w' ***
```

Apologies for not initially including that error. This issue is mainly to acknowledge that anyone using a Pi running Bullseye won't be able to follow the setup instructions to get imgcomp to work.

**Comment by Matthias-Wandel** [comment]
Well, then don't specify parameters in aquire_cmd that libcamera doesn't 
understand.

------ Original Message ------
From: "Austin" ***@***.***>
To: "Matthias-Wandel/imgcomp" ***@***.***>
Cc: "Matthias Wandel" ***@***.***>; "Comment" 
***@***.***>
Sent: 2023-02-28 11:19:17 AM
Subject: Re: [Matthias-Wandel/imgcomp] Not compatible OOB with newer Pis 
that are shipped with libcamera instead of raspisitll (Issue #38)

**Comment by ahartschen** [comment]
Oh, you're right. I thought `-w` _was_ valid. But I just looked at the help and it looks like they only allow `--width` with no shorthand.

With this `acquire_cmd` it is running:

```
aquire_cmd = libcamera-still -q 10 -n -p 1000,0,600,450 --width 1600 --height 1200 -o /ramdisk/out%05d.jpg -t 0 --timelapse 1000
```

**Comment by ahartschen** [comment]
Hm, I am getting a 500 error on `/view.cgi` though. I'm not sure how/if libcamera would impact that.

The logs show this:

```
[Tue Feb 28 08:21:28.537633 2023] [cgi:error] [pid 4302:tid 548197380480] [client <local_ip_address>:61099] End of script output before headers: view.cgi, referer: http://pi.local/
```

**Comment by Matthias-Wandel** [comment]
What you can do is set the QUERY_STRING environment variable to the part 
of the URL after the ?, or if you don't set that variable, it just 
asumes view.cgi with nothing after it.
Run that from the console in the browse directory and tell me what the 
error is.

------ Original Message ------
From: "Austin" ***@***.***>
To: "Matthias-Wandel/imgcomp" ***@***.***>
Cc: "Matthias Wandel" ***@***.***>; "Comment" 
***@***.***>
Sent: 2023-02-28 12:33:27 PM
Subject: Re: [Matthias-Wandel/imgcomp] Not compatible OOB with newer Pis 
that are shipped with libcamera instead of raspisitll (Issue #38)

**Comment by ahartschen** [comment]
I did the following:

```
export QUERY_STRING=230228
./view.cgi
```

And it produced this:

```
Content-Type: text/html

Segmentation fault
```

**Comment by ahartschen** [comment]
I ran `gdb` and it shows the segmentation fault comes from the `CollectDir` method on [this line](https://github.com/Matthias-Wandel/imgcomp/blob/8cd6f99faace5ca71aff92ad7f45dc70e3883bba/browse/view.c#L70). I assume since `a = 0` we're accessing the `-1` index of `HtmlPath` and that is causing the issue? No idea how it's just showing up now though.

**Comment by Matthias-Wandel** [comment]
Uh oh, that’s not useful for debugging.
Sorry, don’t have time to play with this right now, but if you did a debit
build and ran geb on it and told me where it crashes, I’d look at that.

**Comment by ahartschen** [comment]
I did that, see my above comment. Here's a screenshot from the debugging session:

![image](https://user-images.githubusercontent.com/16945037/222006987-010b6f79-22bc-40db-acf2-a27f1567a8fb.png)

**Comment by Matthias-Wandel** [comment]
oops, I see the error.  Change line 69

     for (a=0;HtmlPath[a] && a < 99;a++){
             if (HtmlPath[a-1] == '/' && HtmlPath[a]) LastSlash = a;
         }

To this:

     for (a=1;HtmlPath[a] && a < 99;a++){
             if (HtmlPath[a-1] == '/' && HtmlPath[a]) LastSlash = a;
     }

This is a latent bug, not related to the new image capture program.

------ Original Message ------
From: "Austin" ***@***.***>
To: "Matthias-Wandel/imgcomp" ***@***.***>
Cc: "Matthias Wandel" ***@***.***>; "Comment" 
***@***.***>
Sent: 2023-02-28 7:32:24 PM
Subject: Re: [Matthias-Wandel/imgcomp] Not compatible OOB with newer Pis 
that are shipped with libcamera instead of raspisitll (Issue #38)

**Comment by ahartschen** [comment]
Thanks, it's working! I'm slightly confused how this isn't happening on my other Pi running imgcomp though? Shouldn't everyone hit this bug?

**Comment by Matthias-Wandel** [comment]
Newer compiler, newer OS, so the memory map was sightly different.
If the string is at the start of allocated memory, addressing -1 will 
break it, otherwise completely benign.

Thanks for testing, I'll check in the change -- unless you want to take 
credit for it on github!

------ Original Message ------
From: "Austin" ***@***.***>
To: "Matthias-Wandel/imgcomp" ***@***.***>
Cc: "Matthias Wandel" ***@***.***>; "Comment" 
***@***.***>
Sent: 2023-02-28 9:20:08 PM
Subject: Re: [Matthias-Wandel/imgcomp] Not compatible OOB with newer Pis 
that are shipped with libcamera instead of raspisitll (Issue #38)

**Comment by ahartschen** [comment]
I did a quick PR above. Would you be interested in me checking in changes to support libcamera too?

**Comment by Matthias-Wandel** [comment]
Yes, I would be intereste in that.
but I would also need a hit on how to merge a pull request.  I have done 
it before, but I can't figure out from the user interface how its done 
anymore.

------ Original Message ------
From: "Austin" ***@***.***>
To: "Matthias-Wandel/imgcomp" ***@***.***>
Cc: "Matthias Wandel" ***@***.***>; "Comment" 
***@***.***>
Sent: 2023-02-28 9:33:20 PM
Subject: Re: [Matthias-Wandel/imgcomp] Not compatible OOB with newer Pis 
that are shipped with libcamera instead of raspisitll (Issue #38)

**Comment by ahartschen** [comment]
If you go back to the PR you can click "Reopen pull request" and then you should have a button to merge like the red arrow shows here:

![image](https://user-images.githubusercontent.com/16945037/222025159-46de2c4d-49df-4f8b-be03-64ee11934e10.png)

**Comment by Matthias-Wandel** [comment]
Ah, I get it now.  I elected merge pull request, I didn't know it was 
also a button.

------ Original Message ------
From: "Austin" ***@***.***>
To: "Matthias-Wandel/imgcomp" ***@***.***>
Cc: "Matthias Wandel" ***@***.***>; "Comment" 
***@***.***>
Sent: 2023-02-28 9:59:08 PM
Subject: Re: [Matthias-Wandel/imgcomp] Not compatible OOB with newer Pis 
that are shipped with libcamera instead of raspisitll (Issue #38)

**Comment by Matthias-Wandel** [comment]
libcamera-still support has been added.
That said, using raspistill on bullseye is also a good option, as raspistill can aquire faster than libcamera-still, and higher quality than libcamera-vid
